### PR TITLE
Station topology

### PR DESCRIPTION
**Pull request by onetom**
I retrieved the station names from the SMRT website and organized them into routes.
I used "abbreviated" station names (without spaces and dashes) to make them programming language identifier friendly for later processing.

There is mapping between these abbreviations and the original names in the names.reb file.
A mapping from the numbered station IDs to the station abbreviations are also there in the lines.reb file.

Using SublimeText's fuzzy TAB-autocomplete feature, it was easy to massage the data.

This exercise has already pointed out that the numbering of the stations are not continuous and there are some phantom stations here and there.

As a next step, I'm curious
1, how could graphviz represent these graphs.
2, how write a routing algo like the one on the SMRT website
3, how well autocomplete would work in the browser for entering station names

### CODE REVIEW

**Comment by kaihendry** [comment]
Hi Tamas, I can't believe you are not using vim anymore!!! And shell to rebel is pretty darn funny.

I thought of doing a Graphviz .dot SMRT map, but my initial results looked foreign compared to the SMRT map.

**Comment by kaihendry** [comment]
Accidentally closed this Tamas.

**Comment by miccheng** [comment]
_palm face_

Can u reopen it?

**Comment by kaihendry** [comment]
I merged it already https://github.com/kaihendry/smrt

**Comment by kaihendry** [comment]
I accidentally closed it as I was experimenting with github pages

**Pull request closed without merging**
